feat: add accounts day data entity
decentraland/collections-graph pull request #62
Opened 2022-06-09 18:04 UTC by juanmahidalgo

2022-06-09 19:17 UTC, cazala requested changes

2022-06-09 19:17 UTC, cazala commented on schema.graphql
> +  uniqueCollectors: [String!]!
Also, I know this is not part of the rankings feature, but could we add the `uniqueCollectors` and `uniqueCollectorsTotal` to the `Item` entity as well? This was something that was requested a few times before (know how many holders an item has) I think we could take the change to add it here, since it's the same logic that we are using for accounts.

2022-06-10 09:09 UTC, juanmahidalgo commented on src/modules/analytics/accountsDayData.ts
> +  buyerAccountsDayData.volume = buyerAccountsDayData.volume.plus(sale.price)
ohh yess, good point! updated so we can `earned` and `spent` as the `Account` entity does!

2022-06-10 09:09 UTC, juanmahidalgo commented on schema.graphql
> +  uniqueCollectors: [String!]!
good idea, `...Total`s added and also added and tracked in `Item`

2022-06-10 09:09 UTC, juanmahidalgo commented on src/modules/analytics/creatorsDayData.ts
> +export function getOrCreateCreatorsDayData(timestamp: BigInt, creator: string): CreatorsDayData {
yes! deleted

2022-06-10 14:43 UTC, cazala approved these changes

2022-06-14 15:15 UTC, merged